apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sub-pubsub
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sub-pubsub
    spec:
      containers:
      - name: sub-pubsub
        image: localhost:5000/sub-pubsub
        imagePullPolicy: IfNotPresent
        env:
          - name: PUBSUB_EMULATOR_HOST
            value: "pubsub-svc:8538"
          - name: DATASTORE_PROJECT_ID
            value: "my-project-id"
