apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:dev"
  artifacts:
  - imageName: morimolymoly/pub-pubsub
    docker:
      dockerfilePath: DockerfilePub
deploy:
  kubectl:
    manifests:
      - kubernetes/pub.yaml
