apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:dev"
  artifacts:
  - imageName: morimolymoly/sub-pubsub
    docker:
      dockerfilePath: DockerfileSub
deploy:
  kubectl:
    manifests:
      - kubernetes/sub.yaml
